name: sounds
version: 1.0.0
homepage: https://github.com/bsutton/sounds
documentation: https://github.com/bsutton/sounds/wiki
description: Sounds provide a complete api and Widgets for audio playback and recording. Both iOS and Android are supported.
repository: https://github.com/bsutton/sounds
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'
dependencies: 
  completer_ex: ^3.0.0
  device_info: ^2.0.0
  flutter: 
    sdk: flutter
  flutter_spinkit: ^5.0.0
  future_builder_ex: 1.0.0
  meta: ^1.1.8
  path: ^1.8.0
  provider: ^5.0.0
  sounds_common: ^2.0.0
  stacktrace_impl: ^2.0.0
  uuid: ^3.0.0
dev_dependencies: 
  dcli: ^0.51.5
  effective_dart: ^1.2.1
  flutter_test: 
    sdk: flutter
  lint: ^1.1.1
  pedantic: ^1.9.0
  pub_semver: ^2.0.0
flutter: 
  plugin: 
    platforms: 
      android: 
        package: com.bsutton.sounds
        pluginClass: Sounds
      ios: 
        pluginClass: Sounds
